# Generated by Django 6.1.1 on 2026-09-22 15:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, verbose_name='Business Name')),
                ('legal_name', models.CharField(blank=True, max_length=255, verbose_name='Legal Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Official Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Official Phone')),
                ('address_line_1', models.CharField(blank=True, max_length=255, verbose_name='Address Line 1')),
                ('address_line_2', models.CharField(blank=True, max_length=255, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State / Province')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal Code')),
                ('country', models.CharField(default='India', max_length=100, verbose_name='Country')),
                ('timezone', models.CharField(default='Asia/Kolkata', help_text='IANA timezone identifier for the business (e.g. Asia/Kolkata, UTC, America/New_York).', max_length=50, verbose_name='Timezone')),
                ('currency', models.CharField(default='INR', help_text='Standard ISO 4217 currency code (e.g. INR, USD, EUR).', max_length=10, verbose_name='Currency Code')),
                ('employee_id_enabled', models.BooleanField(default=True, help_text='Enable automated generation of sequential employee identifiers.', verbose_name='Enable Auto Employee IDs')),
                ('employee_id_prefix', models.CharField(default='EMP', help_text='Prefix string attached before the employee number, e.g. EMP, OM.', max_length=20, verbose_name='Employee ID Prefix')),
                ('employee_id_next_number', models.PositiveIntegerField(default=1, help_text='Sequential counter locked during creation to ensure duplicate-free IDs.', verbose_name='Next Employee Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, verbose_name='Branch Name')),
                ('code', models.CharField(max_length=50, verbose_name='Branch Code')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal Code')),
                ('country', models.CharField(default='India', max_length=100, verbose_name='Country')),
                ('timezone', models.CharField(blank=True, help_text='Leave empty to inherit the parent business timezone.', max_length=50, verbose_name='Branch Timezone Override')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='organization.business', verbose_name='Business')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'ordering': ['business', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('role', models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('BUSINESS_ADMIN', 'Business Admin'), ('MANAGER', 'Manager'), ('STAFF', 'Staff')], default='STAFF', max_length=30, verbose_name='Role')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Joined At')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Left At')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organization.business', verbose_name='Business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_memberships', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Business Membership',
                'verbose_name_plural': 'Business Memberships',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, verbose_name='Department Name')),
                ('code', models.CharField(max_length=50, verbose_name='Department Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='organization.business', verbose_name='Business')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['business', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('employee_id', models.CharField(blank=True, help_text='Business-scoped employee code (e.g. EMP001). Optional if business disables employee IDs.', max_length=50, null=True, verbose_name='Employee ID / Code')),
                ('first_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Work Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone Number')),
                ('designation', models.CharField(max_length=100, verbose_name='Designation / Job Title')),
                ('joining_date', models.DateField(verbose_name='Joining Date')),
                ('employment_status', models.CharField(choices=[('ACTIVE', 'Active'), ('PROBATION', 'Probation'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated'), ('RESIGNED', 'Resigned')], default='ACTIVE', max_length=30, verbose_name='Employment Status')),
                ('date_of_exit', models.DateField(blank=True, null=True, verbose_name='Date of Exit')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organization.branch', verbose_name='Branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organization.business', verbose_name='Business')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organization.department', verbose_name='Department')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='organization.employee', verbose_name='Reporting Manager')),
                ('user', models.ForeignKey(blank=True, help_text='Authentication user linked to this employee. Nullable if employee has not been invited yet.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Linked User Account')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('designation', models.CharField(max_length=100, verbose_name='Designation')),
                ('effective_from', models.DateField(verbose_name='Effective From')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='Effective To')),
                ('notes', models.TextField(blank=True, verbose_name='Change Notes')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organization.branch', verbose_name='Branch at this period')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='organization.business', verbose_name='Business')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organization.department', verbose_name='Department at this period')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='organization.employee', verbose_name='Employee')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organization.employee', verbose_name='Manager at this period')),
            ],
            options={
                'verbose_name': 'Employee Assignment',
                'verbose_name_plural': 'Employee Assignments',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['business', 'is_active'], name='idx_branch_biz_active'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('business', 'code'), name='unique_business_branch_code'),
        ),
        migrations.AddIndex(
            model_name='businessmembership',
            index=models.Index(fields=['business', 'role', 'is_active'], name='idx_biz_member_role'),
        ),
        migrations.AddIndex(
            model_name='businessmembership',
            index=models.Index(fields=['user', 'is_active'], name='idx_user_member_active'),
        ),
        migrations.AddConstraint(
            model_name='businessmembership',
            constraint=models.UniqueConstraint(fields=('business', 'user'), name='unique_business_user_membership'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['business', 'is_active'], name='idx_dept_biz_active'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('business', 'name'), name='unique_business_dept_name'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('business', 'code'), name='unique_business_dept_code'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['business', 'employment_status'], name='idx_emp_biz_status'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['business', 'manager'], name='idx_emp_biz_manager'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['business', 'department'], name='idx_emp_biz_dept'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['business', 'branch'], name='idx_emp_biz_branch'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['user'], name='idx_emp_user'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_id__isnull', False)), fields=('business', 'employee_id'), name='unique_business_employee_id'),
        ),
        migrations.AddIndex(
            model_name='employeeassignment',
            index=models.Index(fields=['employee', '-effective_from'], name='idx_emp_assign_eff_from'),
        ),
        migrations.AddIndex(
            model_name='employeeassignment',
            index=models.Index(fields=['business', '-effective_from'], name='idx_biz_assign_eff_from'),
        ),
    ]
