# Generated by Django 6.1.1 on 2026-09-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmembership',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('BUSINESS_ADMIN', 'Business Admin'), ('MANAGER', 'Manager'), ('STAFF', 'Staff'), ('BROKER', 'Broker')], default='STAFF', max_length=30, verbose_name='Role'),
        ),
    ]
