# Generated by Django 6.1.1 on 2026-09-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_businessmembership_role'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['is_active'], name='idx_biz_is_active'),
        ),
    ]
