# Generated by Django 6.1.1 on 2026-09-29 16:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_business_idx_biz_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Permission Key')),
                ('name', models.CharField(max_length=150, verbose_name='Permission Name')),
                ('module', models.CharField(db_index=True, max_length=50, verbose_name='Module Group')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('default_scope', models.CharField(choices=[('GLOBAL', 'Global / SaaS-Wide'), ('ENTERPRISE', 'Enterprise / Business'), ('CENTER', 'Center / Branch'), ('SELF', 'Self / Own Record')], default='CENTER', max_length=30, verbose_name='Default Scope')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['module', 'key'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='status_effective_date',
            field=models.DateField(blank=True, null=True, verbose_name='Status Effective Date'),
        ),
        migrations.AddField(
            model_name='employee',
            name='status_reason',
            field=models.TextField(blank=True, verbose_name='Status Change Reason'),
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=150, verbose_name='Designation Name')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Designation Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designation_records', to='organization.business', verbose_name='Business')),
            ],
            options={
                'verbose_name': 'Designation',
                'verbose_name_plural': 'Designations',
                'ordering': ['business', 'name'],
                'indexes': [models.Index(fields=['business', 'is_active'], name='idx_desig_biz_active')],
                'constraints': [models.UniqueConstraint(fields=('business', 'name'), name='unique_business_designation_name')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=255, verbose_name='Document Title')),
                ('category', models.CharField(choices=[('IDENTITY_PROOF', 'Identity Proof'), ('ADDRESS_PROOF', 'Address Proof'), ('EDUCATION', 'Education Certificate'), ('CONTRACT', 'Employment Contract'), ('OFFER_LETTER', 'Offer Letter'), ('EXPERIENCE', 'Experience Certificate'), ('BANK', 'Bank Document'), ('TAX', 'Tax Document'), ('OTHER', 'Other')], default='OTHER', max_length=50, verbose_name='Category')),
                ('file_url', models.CharField(max_length=1000, verbose_name='File URL / Storage Path')),
                ('file_name', models.CharField(max_length=255, verbose_name='File Name')),
                ('file_size_bytes', models.PositiveIntegerField(default=0, verbose_name='File Size (Bytes)')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Issue Date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=30, verbose_name='Verification Status')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks / Verification Notes')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Soft Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_documents', to='organization.business', verbose_name='Business')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_documents', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='organization.employee', verbose_name='Employee')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL, verbose_name='Verified By')),
            ],
            options={
                'verbose_name': 'Employee Document',
                'verbose_name_plural': 'Employee Documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'is_deleted'], name='idx_emp_doc_active'), models.Index(fields=['business', 'category', 'is_deleted'], name='idx_biz_doc_cat')],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=150, verbose_name='Holiday Name')),
                ('holiday_date', models.DateField(verbose_name='Holiday Date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_optional', models.BooleanField(default=False, verbose_name='Is Optional / Restricted')),
                ('applies_to_all_centres', models.BooleanField(default=True, help_text='If True, holiday applies enterprise-wide. If False, only attached centres observe it.', verbose_name='Applies to All Centres')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='organization.business', verbose_name='Business')),
                ('centres', models.ManyToManyField(blank=True, related_name='holidays', to='organization.branch', verbose_name='Specific Centres')),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'ordering': ['holiday_date', 'name'],
                'indexes': [models.Index(fields=['business', 'holiday_date'], name='idx_holiday_biz_date')],
                'constraints': [models.UniqueConstraint(fields=('business', 'holiday_date', 'name'), name='unique_business_holiday_date_name')],
            },
        ),
        migrations.CreateModel(
            name='ManagerAccessControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_granted', models.BooleanField(default=True, verbose_name='Is Granted')),
                ('scope', models.CharField(choices=[('GLOBAL', 'Global / SaaS-Wide'), ('ENTERPRISE', 'Enterprise / Business'), ('CENTER', 'Center / Branch'), ('SELF', 'Self / Own Record')], default='CENTER', max_length=30, verbose_name='Scope')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_access_controls', to='organization.business', verbose_name='Business')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Granted By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Manager User')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_grants', to='organization.permission', verbose_name='Permission')),
            ],
            options={
                'verbose_name': 'Manager Access Control',
                'verbose_name_plural': 'Manager Access Controls',
                'indexes': [models.Index(fields=['business', 'user', 'is_granted'], name='idx_mgr_access_lookup')],
                'constraints': [models.UniqueConstraint(fields=('business', 'user', 'permission'), name='unique_business_user_permission')],
            },
        ),
    ]
