# Generated by Django 6.1.1 on 2026-09-30 14:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_permission_employee_status_effective_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='currency',
            field=models.CharField(default='INR', max_length=10, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='branch',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Contact Email'),
        ),
        migrations.AddField(
            model_name='branch',
            name='geofence_radius',
            field=models.PositiveIntegerField(default=100, verbose_name='Allowed Geofence Radius (meters)'),
        ),
        migrations.AddField(
            model_name='branch',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='branch',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='branch',
            name='opening_date',
            field=models.DateField(blank=True, null=True, verbose_name='Opening Date'),
        ),
        migrations.AddField(
            model_name='branch',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Contact Phone'),
        ),
        migrations.AddField(
            model_name='branch',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20, verbose_name='Centre Status'),
        ),
        migrations.CreateModel(
            name='EmployeeActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('action_type', models.CharField(max_length=50, verbose_name='Action Type')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('old_value', models.TextField(blank=True, verbose_name='Old Value')),
                ('new_value', models.TextField(blank=True, verbose_name='New Value')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_employee_activities', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_activities', to='organization.business', verbose_name='Business')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='organization.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Employee Activity Log',
                'verbose_name_plural': 'Employee Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', '-created_at'], name='idx_emp_act_created'), models.Index(fields=['business', '-created_at'], name='idx_biz_act_created')],
            },
        ),
    ]
