# Generated by Django 6.1.1 on 2026-09-22 16:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('otp_hash', models.CharField(max_length=255, verbose_name='Hashed OTP')),
                ('purpose', models.CharField(choices=[('ACTIVATION', 'Account Activation'), ('PASSWORD_RESET', 'Password Reset')], max_length=30, verbose_name='Purpose')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Failed Attempts')),
                ('max_attempts', models.PositiveIntegerField(default=3, verbose_name='Maximum Allowed Attempts')),
                ('resend_cooldown_until', models.DateTimeField(blank=True, null=True, verbose_name='Resend Cooldown Until')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is Used / Consumed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User OTP',
                'verbose_name_plural': 'User OTPs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose', 'is_used'], name='idx_otp_user_purpose')],
            },
        ),
    ]
