# Generated by Django 6.1.1 on 2026-09-22 16:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
        ('organization', '0002_alter_businessmembership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='duration_type',
            field=models.CharField(choices=[('FULL_DAY', 'Full Day'), ('FIRST_HALF', 'First Half'), ('SECOND_HALF', 'Second Half')], default='FULL_DAY', max_length=20, verbose_name='Leave Duration'),
        ),
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('annual_days', models.PositiveIntegerField(default=12, verbose_name='Annual Entitlement (Days)')),
                ('carry_forward_days', models.PositiveIntegerField(default=0, verbose_name='Max Carry Forward Days')),
                ('effective_from', models.DateField(verbose_name='Effective From Date')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='Effective To Date')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_policies', to='organization.business', verbose_name='Business')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='leaves.leavetype', verbose_name='Leave Type')),
            ],
            options={
                'verbose_name': 'Leave Policy',
                'verbose_name_plural': 'Leave Policies',
                'ordering': ['business', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('year', models.PositiveIntegerField(verbose_name='Calendar Year')),
                ('allocated_days', models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Allocated Days')),
                ('used_days', models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Used Days')),
                ('pending_days', models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Pending Days')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='organization.employee', verbose_name='Employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='leaves.leavetype', verbose_name='Leave Type')),
            ],
            options={
                'verbose_name': 'Leave Balance',
                'verbose_name_plural': 'Leave Balances',
                'ordering': ['employee', '-year'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'leave_type', 'year'), name='unique_emp_leave_year_balance')],
            },
        ),
    ]
