# Generated by Django 6.1.1 on 2026-10-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LEAVE_STATUS', 'Leave Status Update'), ('PAYROLL_GENERATED', 'Payroll Generated'), ('ATTENDANCE_ALERT', 'Attendance Alert'), ('ANNOUNCEMENT', 'Company Announcement'), ('GENERAL', 'General Notification'), ('MEETING_INVITATION', 'Meeting Invitation'), ('MEETING_UPDATE', 'Meeting Updated / Rescheduled'), ('MEETING_CANCELLED', 'Meeting Cancelled'), ('MEETING_REMINDER', 'Meeting Reminder')], default='GENERAL', max_length=50, verbose_name='Type'),
        ),
    ]
