# Generated by Django 6.1.1 on 2026-09-22 16:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_alter_businessmembership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Plan Name')),
                ('monthly_charge', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monthly Charge')),
                ('max_centres', models.PositiveIntegerField(default=5, help_text='Upper limit of centres the enterprise can operate simultaneously.', verbose_name='Maximum Centres')),
                ('total_employee_capacity', models.PositiveIntegerField(default=100, help_text='Total pool of employee seats across all centres.', verbose_name='Total Employee Capacity')),
                ('features', models.JSONField(blank=True, default=dict, help_text='Key-value feature flags such as attendance, leave, advanced_payroll, reports.', verbose_name='Feature Entitlements')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['monthly_charge', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, verbose_name='Broker Name / Entity')),
                ('referral_code', models.CharField(db_index=True, help_text='Unique code given to enterprises during onboarding.', max_length=50, unique=True, verbose_name='Referral Code')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='Configurable commission percentage for referred subscription revenue.', max_digits=5, verbose_name='Commission Rate (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='broker_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Broker',
                'verbose_name_plural': 'Brokers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('referral_code_used', models.CharField(max_length=50, verbose_name='Referral Code Used')),
                ('referred_at', models.DateTimeField(auto_now_add=True, verbose_name='Referred Timestamp')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='subscriptions.broker', verbose_name='Broker')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='referral', to='organization.business', verbose_name='Referred Enterprise')),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
                'ordering': ['-referred_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TRIAL', 'Trial'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=30, verbose_name='Status')),
                ('start_date', models.DateField(verbose_name='Subscription Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Subscription End Date')),
                ('current_period_start', models.DateField(verbose_name='Period Start Date')),
                ('current_period_end', models.DateField(verbose_name='Period End Date')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to='organization.business', verbose_name='Enterprise')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan', verbose_name='Current Plan')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('action', models.CharField(choices=[('INITIAL', 'Initial Subscription'), ('UPGRADE', 'Plan Upgrade'), ('DOWNGRADE', 'Plan Downgrade'), ('RENEWAL', 'Plan Renewal'), ('CANCEL', 'Cancellation')], max_length=30, verbose_name='Action')),
                ('monthly_charge', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monthly Charge')),
                ('max_centres', models.PositiveIntegerField(verbose_name='Max Centres at Period')),
                ('total_employee_capacity', models.PositiveIntegerField(verbose_name='Capacity at Period')),
                ('effective_from', models.DateField(verbose_name='Effective From Date')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='Effective To Date')),
                ('reason', models.TextField(blank=True, verbose_name='Change Reason')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_history', to='organization.business', verbose_name='Enterprise')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.plan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Subscription History',
                'verbose_name_plural': 'Subscription History Records',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('period_start', models.DateField(verbose_name='Period Start')),
                ('period_end', models.DateField(verbose_name='Period End')),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Commission Amount')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30, verbose_name='Status')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid Timestamp')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='Payment Reference')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='subscriptions.broker', verbose_name='Broker')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='organization.business', verbose_name='Enterprise')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.plan', verbose_name='Plan Billed')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='subscriptions.subscription', verbose_name='Subscription')),
            ],
            options={
                'verbose_name': 'Commission Record',
                'verbose_name_plural': 'Commission Records',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['broker', 'status'], name='idx_comm_broker_status'), models.Index(fields=['business', '-period_start'], name='idx_comm_biz_period')],
            },
        ),
        migrations.CreateModel(
            name='CentreCapacityAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('allocated_capacity', models.PositiveIntegerField(default=0, verbose_name='Allocated Capacity')),
                ('centre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_allocation', to='organization.branch', verbose_name='Centre / Branch')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centre_allocations', to='subscriptions.subscription', verbose_name='Subscription')),
            ],
            options={
                'verbose_name': 'Centre Capacity Allocation',
                'verbose_name_plural': 'Centre Capacity Allocations',
                'indexes': [models.Index(fields=['subscription', 'centre'], name='idx_centre_cap_sub')],
            },
        ),
    ]
