# Generated by Django 6.1.1 on 2026-09-23 16:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_businessmembership_role'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE_PAID', 'Active Paid'), ('ACTIVE', 'Active'), ('PAYMENT_DUE', 'Payment Due'), ('OVERDUE', 'Overdue'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=30, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('billing_date', models.DateField(verbose_name='Billing Date')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Payment Due / Pending'), ('OVERDUE', 'Overdue'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PAID', max_length=30, verbose_name='Payment Status')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid At')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='Payment / Transaction Reference')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='Invoice Number')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='organization.business', verbose_name='Enterprise')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='subscriptions.plan', verbose_name='Plan Billed')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.subscription', verbose_name='Subscription')),
            ],
            options={
                'verbose_name': 'Subscription Payment',
                'verbose_name_plural': 'Subscription Payments',
                'ordering': ['-billing_date'],
                'indexes': [models.Index(fields=['business', 'status'], name='idx_sub_pmt_biz_status'), models.Index(fields=['billing_date', 'status'], name='idx_sub_pmt_date_status')],
            },
        ),
    ]
