# Generated by Django 6.1.1 on 2026-09-29 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_business_idx_biz_is_active'),
        ('subscriptions', '0002_alter_subscription_status_subscriptionpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='broker',
            index=models.Index(fields=['is_active'], name='idx_broker_is_active'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['is_active'], name='idx_plan_is_active'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status'], name='idx_sub_status'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['current_period_end'], name='idx_sub_period_end'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'current_period_end'], name='idx_sub_status_end'),
        ),
    ]
