# Generated by Django 6.1.1 on 2026-10-07 14:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0006_employee_personal_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('event_type', models.CharField(choices=[('ENROLLMENT', 'Face Enrolled'), ('RE_ENROLLMENT', 'Face Re-enrolled'), ('REVOCATION', 'Face Revoked'), ('VERIFICATION_SUCCESS', 'Verification Success'), ('VERIFICATION_FAILED', 'Verification Failed'), ('DEVICE_REGISTERED', 'Device Registered'), ('DEVICE_REVOKED', 'Device Revoked'), ('TEMPLATE_PROVISIONED', 'Template Provisioned to Device')], db_index=True, max_length=30, verbose_name='Event Type')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Audit Details Metadata')),
                ('ip_address', models.CharField(blank=True, max_length=45, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_actions', to=settings.AUTH_USER_MODEL, verbose_name='Actor / User')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_audit_events', to='organization.business', verbose_name='Business')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_audit_events', to='organization.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Biometric Audit Event',
                'verbose_name_plural': 'Biometric Audit Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('device_id', models.CharField(db_index=True, max_length=150, verbose_name='Device Unique Identifier')),
                ('device_name', models.CharField(blank=True, max_length=100, verbose_name='Device Name / Model')),
                ('platform', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS'), ('WEB', 'Web')], default='ANDROID', max_length=20, verbose_name='Platform')),
                ('public_key', models.TextField(blank=True, verbose_name='Device Public Key / Secret for Assertion Verification')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked'), ('PENDING', 'Pending')], db_index=True, default='ACTIVE', max_length=20, verbose_name='Device Status')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Registered At')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='Last Seen At')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Revoked At')),
                ('revocation_reason', models.TextField(blank=True, verbose_name='Revocation Reason')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='organization.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Employee Device',
                'verbose_name_plural': 'Employee Devices',
            },
        ),
        migrations.CreateModel(
            name='BiometricChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('nonce', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Cryptographic Nonce')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Issued At')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Expires At')),
                ('is_used', models.BooleanField(db_index=True, default=False, verbose_name='Is Nonce Used')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Used At')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_challenges', to='organization.employee', verbose_name='Employee')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='biometrics.employeedevice', verbose_name='Device')),
            ],
            options={
                'verbose_name': 'Biometric Challenge',
                'verbose_name_plural': 'Biometric Challenges',
            },
        ),
        migrations.CreateModel(
            name='EmployeeFaceEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('model_id', models.CharField(default='OWNMANAGE-MOBILEFACENET-ARCFACE-128-V1', max_length=100, verbose_name='Model Identifier')),
                ('model_version', models.CharField(default='1.0.0', max_length=20, verbose_name='Model Version')),
                ('detector_version', models.CharField(default='1.0.0', max_length=20, verbose_name='Detector Version')),
                ('preprocessing_version', models.CharField(default='1.0.0', max_length=20, verbose_name='Preprocessing Version')),
                ('embedding_dimension', models.PositiveIntegerField(default=128, verbose_name='Embedding Dimension')),
                ('embedding_format', models.CharField(default='FLOAT32_L2_NORMALIZED', max_length=50, verbose_name='Embedding Format')),
                ('encrypted_embedding', models.TextField(verbose_name='Encrypted Embedding Ciphertext')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked'), ('PENDING', 'Pending'), ('FAILED', 'Failed')], db_index=True, default='ACTIVE', max_length=20, verbose_name='Enrollment Status')),
                ('quality_score', models.FloatField(default=1.0, verbose_name='Enrollment Quality Score')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Enrolled At')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Revoked At')),
                ('revocation_reason', models.TextField(blank=True, verbose_name='Revocation Reason')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_enrollments', to='organization.employee', verbose_name='Employee')),
                ('enrolled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_face_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Enrolled By User')),
            ],
            options={
                'verbose_name': 'Employee Face Enrollment',
                'verbose_name_plural': 'Employee Face Enrollments',
            },
        ),
        migrations.AddIndex(
            model_name='employeedevice',
            index=models.Index(fields=['device_id', 'status'], name='biometrics__device__f5da94_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeedevice',
            constraint=models.UniqueConstraint(fields=('employee', 'device_id'), name='unique_employee_device_id'),
        ),
        migrations.AddIndex(
            model_name='employeefaceenrollment',
            index=models.Index(fields=['employee', 'status'], name='biometrics__employe_0d965c_idx'),
        ),
        migrations.AddIndex(
            model_name='employeefaceenrollment',
            index=models.Index(fields=['model_id', 'status'], name='biometrics__model_i_6a017c_idx'),
        ),
    ]
