# Generated by Django 6.1.1 on 2026-09-22 15:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('attendance_date', models.DateField(verbose_name='Attendance Date')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day'), ('LATE', 'Late'), ('LEAVE', 'On Leave'), ('HOLIDAY', 'Company Holiday'), ('WEEK_OFF', 'Weekly Off')], default='PRESENT', max_length=30, verbose_name='Status')),
                ('total_work_seconds', models.PositiveIntegerField(default=0, help_text='Aggregated active work duration in seconds derived from punch pairs.', verbose_name='Total Work Seconds')),
                ('is_locked', models.BooleanField(default=False, help_text='Locks the day from further check-in edits once payroll for this period is approved.', verbose_name='Is Locked')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_days', to='organization.business', verbose_name='Business')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_days', to='organization.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Attendance Day',
                'verbose_name_plural': 'Attendance Days',
                'ordering': ['-attendance_date', 'employee'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('event_type', models.CharField(choices=[('CHECK_IN', 'Check In'), ('CHECK_OUT', 'Check Out'), ('BREAK_START', 'Break Start'), ('BREAK_END', 'Break End')], max_length=30, verbose_name='Event Type')),
                ('event_time', models.DateTimeField(db_index=True, verbose_name='Event Timestamp (UTC)')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('location_accuracy', models.FloatField(blank=True, null=True, verbose_name='Location Accuracy (Meters)')),
                ('device_id', models.CharField(blank=True, max_length=150, verbose_name='Device ID / Identifier')),
                ('source', models.CharField(choices=[('WEB', 'Web Dashboard'), ('MOBILE', 'Mobile App'), ('BIOMETRIC', 'Biometric Device'), ('MANUAL_ADMIN', 'Manual Admin Entry')], default='WEB', max_length=30, verbose_name='Source Channel')),
                ('notes', models.TextField(blank=True, verbose_name='Event Notes')),
                ('attendance_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='attendance.attendanceday', verbose_name='Attendance Day')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_events', to='organization.business', verbose_name='Business')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_events', to='organization.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Attendance Event',
                'verbose_name_plural': 'Attendance Events',
                'ordering': ['event_time'],
            },
        ),
        migrations.AddIndex(
            model_name='attendanceday',
            index=models.Index(fields=['business', '-attendance_date'], name='idx_att_biz_date'),
        ),
        migrations.AddIndex(
            model_name='attendanceday',
            index=models.Index(fields=['employee', '-attendance_date'], name='idx_att_emp_date'),
        ),
        migrations.AddIndex(
            model_name='attendanceday',
            index=models.Index(fields=['business', 'status'], name='idx_att_biz_status'),
        ),
        migrations.AddConstraint(
            model_name='attendanceday',
            constraint=models.UniqueConstraint(fields=('employee', 'attendance_date'), name='unique_employee_attendance_date'),
        ),
        migrations.AddIndex(
            model_name='attendanceevent',
            index=models.Index(fields=['attendance_day', 'event_time'], name='idx_attevt_day_time'),
        ),
        migrations.AddIndex(
            model_name='attendanceevent',
            index=models.Index(fields=['employee', '-event_time'], name='idx_attevt_emp_time'),
        ),
        migrations.AddIndex(
            model_name='attendanceevent',
            index=models.Index(fields=['business', '-event_time'], name='idx_attevt_biz_time'),
        ),
    ]
