# Generated by Django 6.1.1 on 2026-09-22 16:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('organization', '0002_alter_businessmembership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCorrection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('correction_type', models.CharField(choices=[('CHECK_IN', 'Check In'), ('CHECK_OUT', 'Check Out'), ('STATUS', 'Daily Status')], max_length=30, verbose_name='Correction Type')),
                ('corrected_time', models.DateTimeField(blank=True, null=True, verbose_name='Corrected Timestamp')),
                ('corrected_status', models.CharField(blank=True, choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day'), ('LATE', 'Late'), ('LEAVE', 'On Leave'), ('HOLIDAY', 'Company Holiday'), ('WEEK_OFF', 'Weekly Off')], max_length=30, verbose_name='Corrected Status')),
                ('reason', models.TextField(verbose_name='Reason for Correction')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=30, verbose_name='Status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed Timestamp')),
                ('review_notes', models.TextField(blank=True, verbose_name='Review Notes')),
                ('attendance_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='attendance.attendanceday', verbose_name='Attendance Day')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_corrections', to='organization.business', verbose_name='Business')),
                ('original_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='attendance.attendanceevent', verbose_name='Original Event')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_attendance_corrections', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_attendance_corrections', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
            ],
            options={
                'verbose_name': 'Attendance Correction',
                'verbose_name_plural': 'Attendance Corrections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, verbose_name='Schedule Name')),
                ('start_time', models.TimeField(default='09:00:00', verbose_name='Shift Start Time')),
                ('end_time', models.TimeField(default='18:00:00', verbose_name='Shift End Time')),
                ('is_overnight', models.BooleanField(default=False, help_text='Designates whether the shift crosses midnight (e.g. 22:00 to 06:00).', verbose_name='Is Overnight Shift')),
                ('grace_period_minutes', models.PositiveIntegerField(default=15, help_text='Configurable tolerance window before check-in is flagged as LATE.', verbose_name='Grace Period (Minutes)')),
                ('is_business_default', models.BooleanField(default=False, verbose_name='Is Default Schedule')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='organization.business', verbose_name='Business')),
            ],
            options={
                'verbose_name': 'Work Schedule',
                'verbose_name_plural': 'Work Schedules',
                'ordering': ['business', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeScheduleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('effective_from', models.DateField(verbose_name='Effective From Date')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='Effective To Date')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_assignments', to='organization.employee', verbose_name='Employee')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='attendance.workschedule', verbose_name='Work Schedule')),
            ],
            options={
                'verbose_name': 'Employee Schedule Assignment',
                'verbose_name_plural': 'Employee Schedule Assignments',
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['employee', '-effective_from'], name='idx_empsch_eff_from')],
            },
        ),
        migrations.CreateModel(
            name='WorkScheduleDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='Day of Week')),
                ('is_work_day', models.BooleanField(default=True, verbose_name='Is Work Day')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Start Time Override')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End Time Override')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='attendance.workschedule', verbose_name='Schedule')),
            ],
            options={
                'verbose_name': 'Schedule Day Rule',
                'verbose_name_plural': 'Schedule Day Rules',
                'ordering': ['schedule', 'day_of_week'],
                'constraints': [models.UniqueConstraint(fields=('schedule', 'day_of_week'), name='unique_schedule_day_of_week')],
            },
        ),
    ]
