# Generated by Django 6.1.1 on 2026-09-29 16:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancecorrection_workschedule_and_more'),
        ('organization', '0004_permission_employee_status_effective_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('office_start', models.TimeField(default='09:00:00', verbose_name='Office Start Time')),
                ('office_end', models.TimeField(default='18:00:00', verbose_name='Office End Time')),
                ('working_days', models.PositiveSmallIntegerField(default=5, verbose_name='Working Days per Week')),
                ('weekly_off', models.PositiveSmallIntegerField(default=6, help_text='0=Monday, 1=Tuesday, 2=Wednesday, 3=Thursday, 4=Friday, 5=Saturday, 6=Sunday', verbose_name='Weekly Off Day')),
                ('grace_period_minutes', models.PositiveIntegerField(default=15, help_text='Window after shift start where check-in is still considered PRESENT without late penalty.', verbose_name='Grace Period (Minutes)')),
                ('minimum_present_minutes', models.PositiveIntegerField(default=480, help_text='Minimum active work time required for a full day PRESENT status (e.g. 480 min = 8 hours).', verbose_name='Minimum Present Minutes')),
                ('minimum_half_day_minutes', models.PositiveIntegerField(default=240, help_text='Minimum active work time required for HALF_DAY status (e.g. 240 min = 4 hours).', verbose_name='Minimum Half Day Minutes')),
                ('auto_attendance', models.BooleanField(default=True, help_text='Automatically calculate daily attendance status from punch events.', verbose_name='Auto Attendance Enabled')),
                ('allow_center_override', models.BooleanField(default=True, help_text='Whether permitted managers can override specific rules for their assigned centre.', verbose_name='Allow Centre Overrides')),
                ('ot_enabled', models.BooleanField(default=False, verbose_name='Overtime Enabled')),
                ('ot_grace_minutes', models.PositiveIntegerField(default=30, verbose_name='Overtime Grace Minutes')),
                ('ot_approval_required', models.BooleanField(default=True, verbose_name='Overtime Approval Required')),
                ('max_daily_ot_minutes', models.PositiveIntegerField(default=240, verbose_name='Maximum Daily Overtime Minutes')),
                ('allow_normal_punch', models.BooleanField(default=True, verbose_name='Allow Normal Check-In')),
                ('allow_gps', models.BooleanField(default=True, verbose_name='Allow GPS Check-In')),
                ('allow_geofencing', models.BooleanField(default=False, verbose_name='Allow Geofencing')),
                ('allow_qr', models.BooleanField(default=False, verbose_name='Allow QR Code')),
                ('allow_face_recognition', models.BooleanField(default=False, verbose_name='Allow Face Recognition')),
                ('allow_biometric', models.BooleanField(default=False, verbose_name='Allow Biometric Device')),
                ('extra_settings', models.JSONField(blank=True, default=dict, verbose_name='Extensible Metadata')),
            ],
            options={
                'verbose_name': 'Attendance Policy',
                'verbose_name_plural': 'Attendance Policies',
            },
        ),
        migrations.CreateModel(
            name='AttendancePolicyOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('office_start', models.TimeField(blank=True, null=True, verbose_name='Office Start Time Override')),
                ('office_end', models.TimeField(blank=True, null=True, verbose_name='Office End Time Override')),
                ('grace_period_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Grace Period Override')),
                ('minimum_present_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Minimum Present Override')),
                ('minimum_half_day_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Minimum Half-Day Override')),
                ('weekly_off', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Weekly Off Override')),
                ('auto_attendance', models.BooleanField(blank=True, null=True, verbose_name='Auto Attendance Override')),
                ('ot_enabled', models.BooleanField(blank=True, null=True, verbose_name='Overtime Enabled Override')),
                ('ot_grace_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='OT Grace Override')),
                ('extra_settings', models.JSONField(blank=True, default=dict, verbose_name='Custom Centre Settings')),
            ],
            options={
                'verbose_name': 'Attendance Policy Override',
                'verbose_name_plural': 'Attendance Policy Overrides',
            },
        ),
        migrations.AddField(
            model_name='attendanceday',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_days', to='organization.branch', verbose_name='Centre / Branch'),
        ),
        migrations.AddField(
            model_name='attendanceday',
            name='early_leave_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Early Departure Minutes'),
        ),
        migrations.AddField(
            model_name='attendanceday',
            name='late_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Late Arrival Minutes'),
        ),
        migrations.AddField(
            model_name='attendanceday',
            name='overtime_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='Overtime Seconds'),
        ),
        migrations.AlterField(
            model_name='attendancecorrection',
            name='corrected_status',
            field=models.CharField(blank=True, choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day'), ('LATE', 'Late'), ('LEAVE_EARLY', 'Leave Early'), ('OVERTIME', 'Overtime'), ('LEAVE', 'On Leave'), ('HOLIDAY', 'Company Holiday'), ('WEEK_OFF', 'Weekly Off'), ('NOT_MARKED', 'Not Marked')], max_length=30, verbose_name='Corrected Status'),
        ),
        migrations.AlterField(
            model_name='attendanceday',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day'), ('LATE', 'Late'), ('LEAVE_EARLY', 'Leave Early'), ('OVERTIME', 'Overtime'), ('LEAVE', 'On Leave'), ('HOLIDAY', 'Company Holiday'), ('WEEK_OFF', 'Weekly Off'), ('NOT_MARKED', 'Not Marked')], default='PRESENT', max_length=30, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='attendanceday',
            index=models.Index(fields=['centre', '-attendance_date'], name='idx_att_centre_date'),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_policy', to='organization.business', verbose_name='Business'),
        ),
        migrations.AddField(
            model_name='attendancepolicyoverride',
            name='centre',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_policy_override', to='organization.branch', verbose_name='Centre / Branch'),
        ),
    ]
