# Generated by Django 6.1.1 on 2026-09-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancepolicy_attendancepolicyoverride_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepolicy',
            name='break_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Break End Time'),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='break_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Break Start Time'),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='daily_schedules',
            field=models.JSONField(blank=True, default=dict, help_text='Per-day working hours map, e.g. {"0": {"start": "09:00", "end": "18:00"}}', verbose_name='Daily Schedules'),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='early_checkout_threshold_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Early Checkout Threshold (Minutes)'),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='gps_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='GPS Latitude'),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='gps_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='GPS Longitude'),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='gps_radius_meters',
            field=models.PositiveIntegerField(default=100, verbose_name='GPS Allowed Radius (meters)'),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='late_threshold_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Late Threshold (Minutes)'),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='location_required_checkin',
            field=models.BooleanField(default=False, verbose_name='Location Required Check-in'),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='location_required_checkout',
            field=models.BooleanField(default=False, verbose_name='Location Required Check-out'),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='weekly_off_days',
            field=models.JSONField(blank=True, default=list, help_text='List of weekly off days [0..6] where 0=Monday, 6=Sunday. Allows 0 to 7 days.', verbose_name='Weekly Off Days'),
        ),
        migrations.AddField(
            model_name='attendancepolicyoverride',
            name='allow_biometric',
            field=models.BooleanField(blank=True, null=True, verbose_name='Allow Biometric Override'),
        ),
        migrations.AddField(
            model_name='attendancepolicyoverride',
            name='allow_face_recognition',
            field=models.BooleanField(blank=True, null=True, verbose_name='Allow Face Override'),
        ),
        migrations.AddField(
            model_name='attendancepolicyoverride',
            name='allow_geofencing',
            field=models.BooleanField(blank=True, null=True, verbose_name='Allow Geofencing Override'),
        ),
        migrations.AddField(
            model_name='attendancepolicyoverride',
            name='allow_gps',
            field=models.BooleanField(blank=True, null=True, verbose_name='Allow GPS Override'),
        ),
        migrations.AddField(
            model_name='attendancepolicyoverride',
            name='allow_normal_punch',
            field=models.BooleanField(blank=True, null=True, verbose_name='Allow Normal Punch Override'),
        ),
        migrations.AddField(
            model_name='attendancepolicyoverride',
            name='allow_qr',
            field=models.BooleanField(blank=True, null=True, verbose_name='Allow QR Override'),
        ),
        migrations.AddField(
            model_name='attendancepolicyoverride',
            name='break_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Break End Override'),
        ),
        migrations.AddField(
            model_name='attendancepolicyoverride',
            name='break_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Break Start Override'),
        ),
        migrations.AddField(
            model_name='attendancepolicyoverride',
            name='daily_schedules',
            field=models.JSONField(blank=True, null=True, verbose_name='Daily Schedules Override'),
        ),
        migrations.AddField(
            model_name='attendancepolicyoverride',
            name='early_checkout_threshold_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Early Checkout Threshold Override'),
        ),
        migrations.AddField(
            model_name='attendancepolicyoverride',
            name='gps_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='GPS Latitude Override'),
        ),
        migrations.AddField(
            model_name='attendancepolicyoverride',
            name='gps_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='GPS Longitude Override'),
        ),
        migrations.AddField(
            model_name='attendancepolicyoverride',
            name='gps_radius_meters',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='GPS Radius Override'),
        ),
        migrations.AddField(
            model_name='attendancepolicyoverride',
            name='late_threshold_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Late Threshold Override'),
        ),
        migrations.AddField(
            model_name='attendancepolicyoverride',
            name='location_required_checkin',
            field=models.BooleanField(blank=True, null=True, verbose_name='Location Required Check-in Override'),
        ),
        migrations.AddField(
            model_name='attendancepolicyoverride',
            name='location_required_checkout',
            field=models.BooleanField(blank=True, null=True, verbose_name='Location Required Check-out Override'),
        ),
        migrations.AddField(
            model_name='attendancepolicyoverride',
            name='weekly_off_days',
            field=models.JSONField(blank=True, null=True, verbose_name='Weekly Off Days Override'),
        ),
        migrations.AlterField(
            model_name='attendancepolicy',
            name='weekly_off',
            field=models.PositiveSmallIntegerField(default=6, help_text='Legacy single weekly off: 0=Monday, 6=Sunday', verbose_name='Weekly Off Day'),
        ),
    ]
