# Generated by Django 6.1.1 on 2026-10-07 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendancepolicy_break_end_and_more'),
        ('organization', '0006_employee_personal_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceday',
            name='attendance_method',
            field=models.CharField(choices=[('NORMAL', 'Normal Punch'), ('QR', 'QR Code'), ('FACE', 'Face Recognition')], default='NORMAL', max_length=30, verbose_name='Attendance Method'),
        ),
        migrations.AddField(
            model_name='attendanceday',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Check In Timestamp'),
        ),
        migrations.AddField(
            model_name='attendanceday',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Check Out Timestamp'),
        ),
        migrations.AddField(
            model_name='attendanceday',
            name='is_overridden',
            field=models.BooleanField(default=False, verbose_name='Is Overridden / Manually Edited'),
        ),
        migrations.AddField(
            model_name='attendanceday',
            name='location_verified',
            field=models.BooleanField(default=False, verbose_name='Location Verified'),
        ),
        migrations.AddField(
            model_name='attendanceday',
            name='original_check_in',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Original Check In'),
        ),
        migrations.AddField(
            model_name='attendanceday',
            name='original_check_out',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Original Check Out'),
        ),
        migrations.AddField(
            model_name='attendanceday',
            name='original_status',
            field=models.CharField(blank=True, max_length=30, verbose_name='Original Status'),
        ),
        migrations.AddField(
            model_name='attendanceday',
            name='overridden_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Overridden At'),
        ),
        migrations.AddField(
            model_name='attendanceday',
            name='overridden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_overrides', to=settings.AUTH_USER_MODEL, verbose_name='Overridden By'),
        ),
        migrations.AddField(
            model_name='attendanceday',
            name='override_reason',
            field=models.TextField(blank=True, verbose_name='Override Reason'),
        ),
        migrations.AddField(
            model_name='attendanceday',
            name='verification_metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Verification Metadata'),
        ),
        migrations.AddField(
            model_name='attendanceevent',
            name='attendance_method',
            field=models.CharField(choices=[('NORMAL', 'Normal Punch'), ('QR', 'QR Code'), ('FACE', 'Face Recognition')], default='NORMAL', max_length=30, verbose_name='Attendance Method'),
        ),
        migrations.AddField(
            model_name='attendanceevent',
            name='location_verified',
            field=models.BooleanField(default=False, verbose_name='Location Verified'),
        ),
        migrations.AddField(
            model_name='attendanceevent',
            name='verification_metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Verification Metadata'),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='ot_rate_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Overtime Rate Multiplier'),
        ),
        migrations.AddField(
            model_name='attendancepolicyoverride',
            name='ot_rate_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Overtime Rate Multiplier Override'),
        ),
        migrations.AddIndex(
            model_name='attendanceday',
            index=models.Index(fields=['business', 'attendance_method'], name='idx_att_biz_method'),
        ),
    ]
