# Generated by Django 6.1.1 on 2026-10-10 13:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendanceday_attendance_method_and_more'),
        ('organization', '0008_add_meetings_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWorkingHour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='Day of Week')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Is Working Day Enabled')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Shift Start Time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Shift End Time')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='Break Start Time')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='Break End Time')),
                ('is_override', models.BooleanField(default=False, verbose_name='Is Employee Custom Override')),
                ('configuration_source', models.CharField(choices=[('CENTRE', 'Inherited from Centre'), ('ENTERPRISE', 'Inherited from Enterprise'), ('EMPLOYEE', 'Employee Override')], default='CENTRE', max_length=50, verbose_name='Configuration Source')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='organization.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Employee Working Hour',
                'verbose_name_plural': 'Employee Working Hours',
                'ordering': ['employee', 'day_of_week'],
                'indexes': [models.Index(fields=['employee', 'day_of_week'], name='idx_emp_weekday_wh')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'day_of_week'), name='unique_employee_weekday_working_hour')],
            },
        ),
    ]
