# Generated by Django 6.1.1 on 2026-10-10 18:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_employeeworkinghour'),
        ('organization', '0008_add_meetings_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceQRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('token', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Cryptographic Token')),
                ('code_payload', models.TextField(verbose_name='Full QR Code Payload')),
                ('validity_period', models.CharField(choices=[('DYNAMIC', 'Dynamic (Short-Lived)'), ('DAILY', 'Daily (Calendar Day)'), ('WEEKLY', 'Weekly (Calendar Week)'), ('MONTHLY', 'Monthly (Calendar Month)')], db_index=True, default='DYNAMIC', max_length=20, verbose_name='Validity Period')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Expiry Timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('is_revoked', models.BooleanField(db_index=True, default=False, verbose_name='Is Revoked')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Revoked At')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Security and Policy Metadata')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_qr_codes', to='organization.business', verbose_name='Business')),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_qr_codes', to='organization.branch', verbose_name='Centre / Branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attendance_qrs', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_attendance_qrs', to=settings.AUTH_USER_MODEL, verbose_name='Revoked By')),
            ],
            options={
                'verbose_name': 'Attendance QR Code',
                'verbose_name_plural': 'Attendance QR Codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['centre', 'is_active', 'expires_at'], name='idx_qr_cen_act_exp'), models.Index(fields=['business', 'expires_at'], name='idx_qr_biz_exp'), models.Index(fields=['token', 'is_active', 'is_revoked'], name='idx_qr_tok_act_rev')],
            },
        ),
    ]
