# Generated by Django 6.1.1 on 2026-09-22 15:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('period_start', models.DateField(verbose_name='Period Start Date')),
                ('period_end', models.DateField(verbose_name='Period End Date')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Gross Amount')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Deductions')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Net Amount Payable')),
                ('currency', models.CharField(default='INR', max_length=10, verbose_name='Currency')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSED', 'Processed'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30, verbose_name='Payroll Status')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Generated At')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrolls', to='organization.business', verbose_name='Business')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrolls', to='organization.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Payroll',
                'verbose_name_plural': 'Payrolls',
                'ordering': ['-period_start', 'employee'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('storage_path', models.CharField(blank=True, max_length=500, verbose_name='Supabase Storage Path')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='File Name')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Document Generation Timestamp')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='organization.business', verbose_name='Business')),
                ('payroll', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payslip', to='payroll.payroll', verbose_name='Payroll Record')),
            ],
            options={
                'verbose_name': 'Payslip',
                'verbose_name_plural': 'Payslips',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('effective_from', models.DateField(verbose_name='Effective From Date')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='Effective To Date')),
                ('basic_salary', models.DecimalField(decimal_places=2, help_text='Fixed basic salary component.', max_digits=12, verbose_name='Basic Salary Amount')),
                ('currency', models.CharField(default='INR', max_length=10, verbose_name='Currency')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_structures', to='organization.business', verbose_name='Business')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_structures', to='organization.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Salary Structure',
                'verbose_name_plural': 'Salary Structures',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['business', '-period_start', '-period_end'], name='idx_pay_biz_period'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['employee', '-period_start'], name='idx_pay_emp_period'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['business', 'status'], name='idx_pay_biz_status'),
        ),
        migrations.AddConstraint(
            model_name='payroll',
            constraint=models.UniqueConstraint(fields=('employee', 'period_start', 'period_end'), name='unique_employee_payroll_period'),
        ),
        migrations.AddConstraint(
            model_name='payroll',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='check_payroll_period_valid'),
        ),
        migrations.AddIndex(
            model_name='salarystructure',
            index=models.Index(fields=['employee', '-effective_from'], name='idx_sal_emp_eff_from'),
        ),
        migrations.AddIndex(
            model_name='salarystructure',
            index=models.Index(fields=['business', '-effective_from'], name='idx_sal_biz_eff_from'),
        ),
    ]
