# Generated by Django 6.1.1 on 2026-09-22 16:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_businessmembership_role'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='half_days',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Half Days'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='ot_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Overtime Hours'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='paid_days',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=5, verbose_name='Paid Days'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='salary_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='Frozen Salary Snapshot'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='unpaid_days',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Unpaid Days'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='working_days',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Total Working Days'),
        ),
        migrations.CreateModel(
            name='EmployeeSalaryAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('effective_from', models.DateField(verbose_name='Effective From Date')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='Effective To Date')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_assignments', to='organization.employee', verbose_name='Employee')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='payroll.salarystructure', verbose_name='Salary Structure')),
            ],
            options={
                'verbose_name': 'Employee Salary Assignment',
                'verbose_name_plural': 'Employee Salary Assignments',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, verbose_name='Component Name')),
                ('component_type', models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction')], default='EARNING', max_length=20, verbose_name='Component Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='payroll.salarystructure', verbose_name='Salary Structure')),
            ],
            options={
                'verbose_name': 'Salary Component',
                'verbose_name_plural': 'Salary Components',
            },
        ),
    ]
