# Generated by Django 6.1.1 on 2026-09-29 16:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_permission_employee_status_effective_date_and_more'),
        ('payroll', '0002_payroll_half_days_payroll_ot_hours_payroll_paid_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('period_start', models.DateField(verbose_name='Period Start Date')),
                ('period_end', models.DateField(verbose_name='Period End Date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CALCULATING', 'Calculating'), ('REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('FINALIZED', 'Finalized'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30, verbose_name='Run Status')),
                ('total_employees', models.PositiveIntegerField(default=0, verbose_name='Total Employees Processed')),
                ('total_gross', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Total Gross Amount')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Total Deductions')),
                ('total_net', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Total Net Amount')),
                ('finalized_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalized Timestamp')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payroll_runs', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='organization.business', verbose_name='Business')),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs', to='organization.branch', verbose_name='Centre / Branch')),
            ],
            options={
                'verbose_name': 'Payroll Run',
                'verbose_name_plural': 'Payroll Runs',
                'ordering': ['-period_start', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payroll',
            name='payroll_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrolls', to='payroll.payrollrun', verbose_name='Batch Payroll Run'),
        ),
        migrations.CreateModel(
            name='SalaryRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('effective_from', models.DateField(verbose_name='Effective From Date')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='Effective To Date')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Base Monthly Salary')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Hourly Rate')),
                ('ot_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Overtime Hourly Rate')),
                ('currency', models.CharField(default='INR', max_length=10, verbose_name='Currency')),
                ('allowances', models.JSONField(blank=True, default=dict, help_text='Itemized allowances, e.g. {"hra": 5000, "conveyance": 2000, "medical": 1250}', verbose_name='Allowances Breakdown')),
                ('deduction_rules', models.JSONField(blank=True, default=dict, help_text='Itemized deductions, e.g. {"pf": 1800, "tax": 1000, "esi": 350}', verbose_name='Deductions Breakdown')),
                ('reason', models.TextField(blank=True, verbose_name='Revision Reason')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_revisions', to='organization.business', verbose_name='Business')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_revisions', to='organization.employee', verbose_name='Employee')),
                ('revised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_revisions_authored', to=settings.AUTH_USER_MODEL, verbose_name='Revised By')),
            ],
            options={
                'verbose_name': 'Salary Revision',
                'verbose_name_plural': 'Salary Revisions',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['business', '-period_start'], name='idx_prun_biz_period'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['centre', '-period_start'], name='idx_prun_centre_period'),
        ),
        migrations.AddIndex(
            model_name='salaryrevision',
            index=models.Index(fields=['employee', '-effective_from'], name='idx_salrev_emp_eff'),
        ),
        migrations.AddIndex(
            model_name='salaryrevision',
            index=models.Index(fields=['business', '-effective_from'], name='idx_salrev_biz_eff'),
        ),
    ]
