# Generated by Django 6.1.1 on 2026-09-30 14:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_branch_currency_branch_email_branch_geofence_radius_and_more'),
        ('payroll', '0003_payrollrun_payroll_payroll_run_salaryrevision_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCompensationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=150, verbose_name='Component Name')),
                ('component_type', models.CharField(choices=[('EARNING', 'Earning'), ('BONUS', 'Bonus'), ('ALLOWANCE', 'Allowance'), ('DEDUCTION', 'Deduction'), ('OVERTIME', 'Overtime')], default='EARNING', max_length=20, verbose_name='Component Type')),
                ('calculation_type', models.CharField(choices=[('FIXED_AMOUNT', 'Fixed Amount'), ('PERCENTAGE', 'Percentage')], default='FIXED_AMOUNT', max_length=20, verbose_name='Calculation Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount or Percentage Value')),
                ('effective_from', models.DateField(verbose_name='Effective From Date')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='Effective To Date')),
                ('reason', models.TextField(blank=True, verbose_name='Reason')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_items', to='organization.business', verbose_name='Business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_compensation_items', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_items', to='organization.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Employee Compensation Item',
                'verbose_name_plural': 'Employee Compensation Items',
                'ordering': ['-effective_from', 'name'],
                'indexes': [models.Index(fields=['employee', 'is_active', '-effective_from'], name='idx_comp_emp_act_eff'), models.Index(fields=['business', 'component_type'], name='idx_comp_biz_type')],
            },
        ),
    ]
