# Generated by Django 6.1.1 on 2026-10-05 16:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_employeecompensationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecompensationitem',
            name='frequency',
            field=models.CharField(choices=[('RECURRING', 'Recurring Monthly'), ('ONE_TIME', 'One-Time')], default='RECURRING', help_text='RECURRING components recur monthly. ONE_TIME components apply only to their specific effective period.', max_length=20, verbose_name='Payment Frequency'),
        ),
        migrations.CreateModel(
            name='PayrollLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=150, verbose_name='Component Name')),
                ('line_type', models.CharField(choices=[('BASIC', 'Base Salary'), ('EARNING', 'Earning'), ('ALLOWANCE', 'Allowance'), ('BONUS', 'Bonus'), ('DEDUCTION', 'Deduction'), ('OVERTIME', 'Overtime'), ('UNPAID_LEAVE', 'Unpaid Leave Deduction'), ('PENALTY', 'Penalty'), ('OTHER', 'Other')], default='EARNING', max_length=30, verbose_name='Line Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Unit / Hourly Rate')),
                ('units', models.DecimalField(decimal_places=2, default=1.0, max_digits=8, verbose_name='Units / Hours / Days')),
                ('is_deduction', models.BooleanField(default=False, verbose_name='Is Deduction')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='payroll.payroll', verbose_name='Payroll Record')),
                ('source_compensation_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_lines', to='payroll.employeecompensationitem', verbose_name='Source Compensation Item')),
            ],
            options={
                'verbose_name': 'Payroll Line Item',
                'verbose_name_plural': 'Payroll Line Items',
                'ordering': ['is_deduction', 'name'],
                'indexes': [models.Index(fields=['payroll', 'is_deduction'], name='idx_payline_payroll_ded')],
            },
        ),
    ]
