# Generated by Django 6.1.1 on 2026-10-09 13:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_add_face_enrollment_permission'),
        ('payroll', '0005_employeecompensationitem_frequency_payrolllineitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='schedule_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='Frozen Schedule Snapshot'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='expected_payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expected Payment Date'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='generation_mode',
            field=models.CharField(choices=[('MANUAL', 'Manual Generation'), ('AUTOMATIC_DRAFT_AFTER_PERIOD_END', 'Automatic Draft After Period End'), ('AUTOMATIC_DRAFT_ON_CONFIGURED_DATE', 'Automatic Draft on Configured Date'), ('AUTOMATIC_DRAFT_BEFORE_PERIOD_END', 'Automatic Draft Before Period End')], default='MANUAL', max_length=50, verbose_name='Generation Mode'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='pay_frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('FORTNIGHTLY', 'Fortnightly'), ('MONTHLY_CALENDAR', 'Monthly — Calendar'), ('MONTHLY_CUSTOM', 'Monthly — Custom Cycle'), ('CUSTOM_PERIOD', 'Custom Period')], default='MONTHLY_CALENDAR', max_length=50, verbose_name='Pay Frequency'),
        ),
        migrations.CreateModel(
            name='PayrollScheduleConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('scope', models.CharField(choices=[('ENTERPRISE', 'Enterprise Default'), ('CENTRE', 'Centre Override'), ('EMPLOYEE', 'Employee Override')], default='ENTERPRISE', max_length=20, verbose_name='Configuration Scope')),
                ('has_override', models.BooleanField(default=True, help_text='When False, explicitly inherits parent settings (centre inherits enterprise; employee inherits centre).', verbose_name='Has Active Custom Override')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('effective_from', models.DateField(default=django.utils.timezone.now, verbose_name='Effective From Date')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='Effective To Date')),
                ('compensation_type', models.CharField(choices=[('MONTHLY_SALARY', 'Fixed Monthly Salary'), ('DAILY_WAGE', 'Daily Wage'), ('HOURLY_WAGE', 'Hourly Wage'), ('FIXED_CONTRACT', 'Fixed Contract Amount')], default='MONTHLY_SALARY', max_length=30, verbose_name='Compensation Type')),
                ('pay_frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('FORTNIGHTLY', 'Fortnightly'), ('MONTHLY_CALENDAR', 'Monthly — Calendar'), ('MONTHLY_CUSTOM', 'Monthly — Custom Cycle'), ('CUSTOM_PERIOD', 'Custom Period')], default='MONTHLY_CALENDAR', max_length=30, verbose_name='Pay Frequency')),
                ('week_start_day', models.PositiveSmallIntegerField(default=0, help_text='0=Monday, 1=Tuesday, ..., 6=Sunday', verbose_name='Week Start Day')),
                ('custom_cycle_start_day', models.PositiveSmallIntegerField(default=1, help_text='Day of month (1-31) when recurring cycle starts, e.g. 5th of month to 4th of following month.', verbose_name='Custom Cycle Start Day')),
                ('anchor_date', models.DateField(blank=True, null=True, verbose_name='Anchor Date for Fortnightly / Custom Cycles')),
                ('month_end_rule', models.CharField(choices=[('CLAMP_TO_LAST_DAY', 'Clamp to Last Day of Month'), ('NEXT_AVAILABLE_DAY', 'Next Available Day')], default='CLAMP_TO_LAST_DAY', max_length=30, verbose_name='Month-End Rule')),
                ('generation_mode', models.CharField(choices=[('MANUAL', 'Manual Generation'), ('AUTOMATIC_DRAFT_AFTER_PERIOD_END', 'Automatic Draft After Period End'), ('AUTOMATIC_DRAFT_ON_CONFIGURED_DATE', 'Automatic Draft on Configured Date'), ('AUTOMATIC_DRAFT_BEFORE_PERIOD_END', 'Automatic Draft Before Period End')], default='MANUAL', max_length=50, verbose_name='Generation Mode')),
                ('generation_delay_days', models.PositiveSmallIntegerField(default=1, verbose_name='Generation Processing Delay (Days after period end)')),
                ('generation_day_of_month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Configured Generation Day of Month')),
                ('approval_required', models.BooleanField(default=True, verbose_name='Approval Required Before Finalization')),
                ('approver_role', models.CharField(default='BUSINESS_ADMIN', max_length=30, verbose_name='Approver Role')),
                ('review_deadline_days', models.PositiveSmallIntegerField(default=3, verbose_name='Review Deadline (Days)')),
                ('payment_rule', models.CharField(choices=[('SAME_DAY_AS_PERIOD_END', 'Same Day as Period End'), ('DAYS_AFTER_PERIOD_END', 'Fixed Days After Period End'), ('SPECIFIED_WEEKDAY', 'Specified Weekday'), ('DAY_OF_FOLLOWING_MONTH', 'Fixed Day of Following Month'), ('CUSTOM_RULE', 'Custom Payment Rule'), ('MANUAL', 'Manual Selection')], default='DAY_OF_FOLLOWING_MONTH', max_length=30, verbose_name='Payment Rule')),
                ('payment_offset_days', models.PositiveSmallIntegerField(default=5, verbose_name='Payment Offset Days (after period end)')),
                ('payment_day_of_month', models.PositiveSmallIntegerField(default=7, verbose_name='Payment Day of Following Month')),
                ('payment_weekday', models.PositiveSmallIntegerField(default=4, verbose_name='Specified Payment Weekday (0=Mon, 4=Fri)')),
                ('change_reason', models.TextField(blank=True, verbose_name='Change Reason')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_schedule_configs', to='organization.business', verbose_name='Business')),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_schedule_configs', to='organization.branch', verbose_name='Centre / Branch')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_configs_changed', to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_schedule_configs', to='organization.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Payroll Schedule Configuration',
                'verbose_name_plural': 'Payroll Schedule Configurations',
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='schedule_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs', to='payroll.payrollscheduleconfig', verbose_name='Schedule Configuration'),
        ),
        migrations.CreateModel(
            name='PayrollScheduleHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('scope', models.CharField(max_length=20, verbose_name='Scope')),
                ('snapshot', models.JSONField(default=dict, verbose_name='Configuration Snapshot')),
                ('effective_from', models.DateField(verbose_name='Effective From Date')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='Effective To Date')),
                ('change_reason', models.TextField(blank=True, verbose_name='Change Reason')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_schedule_history', to='organization.business', verbose_name='Business')),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.branch', verbose_name='Centre / Branch')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='payroll.payrollscheduleconfig', verbose_name='Schedule Configuration')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Payroll Schedule History',
                'verbose_name_plural': 'Payroll Schedule History Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payrollscheduleconfig',
            index=models.Index(fields=['business', 'scope', 'is_active'], name='idx_psched_biz_scope'),
        ),
        migrations.AddIndex(
            model_name='payrollscheduleconfig',
            index=models.Index(fields=['centre', 'is_active'], name='idx_psched_centre_act'),
        ),
        migrations.AddIndex(
            model_name='payrollscheduleconfig',
            index=models.Index(fields=['employee', 'is_active'], name='idx_psched_emp_act'),
        ),
    ]
