# Generated by Django 6.1.1 on 2026-10-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_payroll_schedule_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollscheduleconfig',
            name='generation_type',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='MONTHLY', max_length=20, verbose_name='Salary Slip Generation Type'),
        ),
        migrations.AddField(
            model_name='payrollscheduleconfig',
            name='generation_weekday',
            field=models.PositiveSmallIntegerField(default=0, help_text='0=Monday, 1=Tuesday, 2=Wednesday, 3=Thursday, 4=Friday, 5=Saturday, 6=Sunday', verbose_name='Salary Slip Generation Day'),
        ),
    ]
