# Generated by Django 6.1.1 on 2026-10-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_payrollscheduleconfig_generation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrevision',
            name='salary_unit',
            field=models.CharField(choices=[('MONTHLY', 'Per Month'), ('WEEKLY', 'Per Week'), ('DAILY', 'Per Day')], default='MONTHLY', max_length=20, verbose_name='Salary Unit'),
        ),
    ]
