# Generated by Django 6.1.1 on 2026-10-10 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_add_meetings_permissions'),
        ('payroll', '0008_salaryrevision_salary_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecompensationitem',
            name='affects_payroll',
            field=models.BooleanField(default=True, help_text='When True, eligible for payroll calculation. When False, excluded from payroll calculations.', verbose_name='Affects Payroll'),
        ),
        migrations.AddField(
            model_name='employeecompensationitem',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Applied At'),
        ),
        migrations.AddField(
            model_name='employeecompensationitem',
            name='applied_in_payroll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_one_time_components', to='payroll.payroll', verbose_name='Applied In Payroll'),
        ),
        migrations.AddField(
            model_name='employeecompensationitem',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compensation_items', to='organization.branch', verbose_name='Centre / Branch'),
        ),
        migrations.AddField(
            model_name='employeecompensationitem',
            name='is_applied',
            field=models.BooleanField(default=False, help_text='Tracks whether a one-time component has been included in a payroll.', verbose_name='Is Applied'),
        ),
        migrations.AddField(
            model_name='employeecompensationitem',
            name='is_override',
            field=models.BooleanField(default=False, verbose_name='Is Override'),
        ),
        migrations.AddField(
            model_name='employeecompensationitem',
            name='parent_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overrides', to='payroll.employeecompensationitem', verbose_name='Parent Inherited Component'),
        ),
        migrations.AddField(
            model_name='employeecompensationitem',
            name='scope',
            field=models.CharField(choices=[('ENTERPRISE', 'Enterprise Default'), ('CENTRE', 'Centre Override'), ('EMPLOYEE', 'Employee Override')], default='EMPLOYEE', max_length=20, verbose_name='Configuration Scope'),
        ),
        migrations.AlterField(
            model_name='employeecompensationitem',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compensation_items', to='organization.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='employeecompensationitem',
            name='frequency',
            field=models.CharField(choices=[('MONTHLY', 'Recurring Monthly'), ('WEEKLY', 'Recurring Weekly'), ('ONE_TIME', 'One-Time'), ('RECURRING', 'Recurring Monthly')], default='RECURRING', help_text='RECURRING / MONTHLY components recur monthly. WEEKLY components recur weekly. ONE_TIME components apply only to their specific effective period.', max_length=20, verbose_name='Payment Frequency'),
        ),
        migrations.AddIndex(
            model_name='employeecompensationitem',
            index=models.Index(fields=['business', 'scope', 'is_active'], name='idx_comp_biz_scope_act'),
        ),
        migrations.AddIndex(
            model_name='employeecompensationitem',
            index=models.Index(fields=['centre', 'scope', 'is_active'], name='idx_comp_cen_scope_act'),
        ),
    ]
