# Generated by Django 6.1.1 on 2026-10-10 17:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_add_meetings_permissions'),
        ('payroll', '0009_employeecompensationitem_affects_payroll_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='base_salary_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Base Salary Amount Snapshot'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='compensation_type',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Compensation Type Snapshot'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='editing_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Editing Deadline'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finalized Timestamp'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Released Timestamp'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='salary_unit',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Salary Unit Snapshot'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='visibility_policy',
            field=models.CharField(choices=[('ON_FINALIZATION', 'On Payroll Finalization'), ('ON_RELEASE', 'On Explicit Release'), ('ON_PAYMENT_DATE', 'On Payment Date')], default='ON_FINALIZATION', max_length=30, verbose_name='Visibility Policy'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='editing_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Editing Deadline'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='generation_type',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='MONTHLY', max_length=20, verbose_name='Generation Frequency'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Released Timestamp'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='schedule_config_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='Frozen Schedule Snapshot'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='visibility_policy',
            field=models.CharField(choices=[('ON_FINALIZATION', 'On Payroll Finalization'), ('ON_RELEASE', 'On Explicit Release'), ('ON_PAYMENT_DATE', 'On Payment Date')], default='ON_FINALIZATION', max_length=30, verbose_name='Visibility Policy'),
        ),
        migrations.AddField(
            model_name='payrollscheduleconfig',
            name='editable_period_duration',
            field=models.PositiveSmallIntegerField(default=3, help_text='Configured duration for which draft payroll and attendance can receive edits.', verbose_name='Editable Period Duration'),
        ),
        migrations.AddField(
            model_name='payrollscheduleconfig',
            name='editing_period_unit',
            field=models.CharField(choices=[('DAYS', 'Days'), ('HOURS', 'Hours')], default='DAYS', max_length=10, verbose_name='Editing Period Unit'),
        ),
        migrations.AddField(
            model_name='payrollscheduleconfig',
            name='finalization_deadline_days',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Payroll Finalization Deadline (Days)'),
        ),
        migrations.AddField(
            model_name='payrollscheduleconfig',
            name='visibility_policy',
            field=models.CharField(choices=[('ON_FINALIZATION', 'On Payroll Finalization'), ('ON_RELEASE', 'On Explicit Release'), ('ON_PAYMENT_DATE', 'On Payment Date')], default='ON_FINALIZATION', max_length=30, verbose_name='Salary Slip Visibility Policy'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSED', 'In Review'), ('FINALIZED', 'Finalized'), ('RELEASED', 'Released'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30, verbose_name='Payroll Status'),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CALCULATING', 'Calculating'), ('REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('FINALIZED', 'Finalized'), ('RELEASED', 'Released'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30, verbose_name='Run Status'),
        ),
        migrations.CreateModel(
            name='PayrollAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('adjustment_type', models.CharField(choices=[('EARNING', 'Additional Earning / Allowance'), ('BONUS', 'Bonus'), ('DEDUCTION', 'Deduction'), ('OVERTIME', 'Approved Overtime Adjustment'), ('OTHER', 'Other Payroll Adjustment')], default='EARNING', max_length=30, verbose_name='Adjustment Type')),
                ('name', models.CharField(max_length=150, verbose_name='Item Name')),
                ('previous_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Previous Amount')),
                ('new_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='New Amount')),
                ('is_deduction', models.BooleanField(default=False, verbose_name='Is Deduction')),
                ('reason', models.TextField(verbose_name='Adjustment Reason')),
                ('adjusted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_adjustments_authored', to=settings.AUTH_USER_MODEL, verbose_name='Adjusted By')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_adjustments', to='organization.business', verbose_name='Business')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_adjustments', to='organization.employee', verbose_name='Employee')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='payroll.payroll', verbose_name='Payroll Record')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='payroll.payrollrun', verbose_name='Payroll Run')),
            ],
            options={
                'verbose_name': 'Payroll Adjustment',
                'verbose_name_plural': 'Payroll Adjustments',
                'ordering': ['-created_at'],
            },
        ),
    ]
