# Generated by Django 6.1.1 on 2026-10-10 18:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_add_meetings_permissions'),
        ('payroll', '0010_payroll_base_salary_amount_payroll_compensation_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrolladjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('EARNING', 'Additional Earning'), ('ALLOWANCE', 'Additional Allowance'), ('BONUS', 'Bonus'), ('DEDUCTION', 'Deduction'), ('OVERTIME', 'Approved Overtime Adjustment'), ('OTHER', 'Other Payroll Adjustment')], default='EARNING', max_length=30, verbose_name='Adjustment Type'),
        ),
        migrations.CreateModel(
            name='PayrollException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('attendance_date', models.DateField(verbose_name='Attendance Date')),
                ('attendance_status', models.CharField(default='ABSENT', max_length=30, verbose_name='Attendance Status')),
                ('scheduled_hours', models.DecimalField(decimal_places=2, default=8.0, max_digits=5, verbose_name='Scheduled Working Hours')),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Actual Working Hours')),
                ('exception_type', models.CharField(choices=[('ABSENT', 'Missing Attendance / Confirmed Absence'), ('LATE', 'Late Arrival Beyond Grace Period'), ('HALF_DAY', 'Half-Day Attendance'), ('LEAVE_EARLY', 'Early Departure'), ('UNPAID_LEAVE', 'Approved Unpaid Leave'), ('HOLIDAY_WORK', 'Work on Public Holiday'), ('WEEK_OFF_WORK', 'Work on Weekly Off'), ('PENDING_LEAVE', 'Unresolved Pending Leave Request'), ('OTHER', 'Other Exception')], default='ABSENT', max_length=30, verbose_name='Exception Type')),
                ('exception_reason', models.CharField(max_length=255, verbose_name='Exception Reason')),
                ('proposed_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Proposed Amount')),
                ('is_deduction', models.BooleanField(default=True, verbose_name='Is Deduction')),
                ('policy_applied', models.CharField(blank=True, default='', max_length=255, verbose_name='Policy Applied')),
                ('review_status', models.CharField(choices=[('CALCULATED', 'Calculated (Default Applied)'), ('AWAITING_REVIEW', 'Awaiting Review'), ('APPROVED', 'Approved by Manager'), ('WAIVED', 'Waived by Manager'), ('REJECTED', 'Rejected by Manager')], default='AWAITING_REVIEW', max_length=30, verbose_name='Review Status')),
                ('decision_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Final Decision Amount')),
                ('decision_at', models.DateTimeField(blank=True, null=True, verbose_name='Decision Timestamp')),
                ('decision_reason', models.TextField(blank=True, default='', verbose_name='Decision Reason / Audit Comment')),
                ('is_applied_to_payroll', models.BooleanField(default=True, verbose_name='Is Applied to Payroll')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_exceptions', to='organization.business', verbose_name='Business')),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_exceptions', to='organization.branch', verbose_name='Centre / Branch')),
                ('decision_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payroll_exceptions', to=settings.AUTH_USER_MODEL, verbose_name='Decision Author')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_exceptions', to='organization.employee', verbose_name='Employee')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='payroll.payroll', verbose_name='Payroll Record')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='payroll.payrollrun', verbose_name='Payroll Run')),
            ],
            options={
                'verbose_name': 'Payroll Exception',
                'verbose_name_plural': 'Payroll Exceptions',
                'ordering': ['attendance_date', 'employee'],
                'indexes': [models.Index(fields=['payroll_run', 'review_status'], name='payroll_pay_payroll_99d333_idx'), models.Index(fields=['employee', 'attendance_date'], name='payroll_pay_employe_03ed3b_idx')],
                'constraints': [models.UniqueConstraint(fields=('payroll', 'attendance_date', 'exception_type'), name='unique_payroll_attendance_exception')],
            },
        ),
    ]
