# Generated by Django 6.1.1 on 2026-10-09 16:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0007_add_face_enrollment_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=255, verbose_name='Meeting Title')),
                ('description', models.TextField(blank=True, verbose_name='Agenda / Description')),
                ('meeting_date', models.DateField(db_index=True, verbose_name='Meeting Date')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50, verbose_name='Timezone')),
                ('location_type', models.CharField(choices=[('ONLINE', 'Online / Video Call'), ('IN_PERSON', 'In Person'), ('OTHER', 'Other / Custom')], default='ONLINE', max_length=30, verbose_name='Location Type')),
                ('location_details', models.CharField(blank=True, max_length=255, verbose_name='Location Details / Room')),
                ('meeting_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Online Meeting Link')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=30, verbose_name='Lifecycle Status')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Cancellation Reason')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelled At')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='organization.branch', verbose_name='Centre / Branch Scope')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='organization.business', verbose_name='Business / Tenant')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Cancelled By')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organized_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Organizer User')),
                ('organizer_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_meetings', to='organization.employee', verbose_name='Organizer Employee Profile')),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
                'ordering': ['meeting_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='MeetingAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('event_type', models.CharField(choices=[('CREATED', 'Meeting Created'), ('RESCHEDULED', 'Meeting Rescheduled'), ('UPDATED', 'Meeting Details Updated'), ('CANCELLED', 'Meeting Cancelled'), ('PARTICIPANT_ADDED', 'Participant Added'), ('PARTICIPANT_REMOVED', 'Participant Removed'), ('RESPONSE_CHANGED', 'RSVP Response Changed')], max_length=50, verbose_name='Event Type')),
                ('summary', models.CharField(max_length=255, verbose_name='Summary')),
                ('diff_data', models.JSONField(blank=True, default=dict, verbose_name='Diff / Snapshot Data')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='meetings.meeting', verbose_name='Meeting')),
            ],
            options={
                'verbose_name': 'Meeting Audit Event',
                'verbose_name_plural': 'Meeting Audit Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingExternalGuest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Guest Email Address')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Guest Name')),
                ('response_status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('TENTATIVE', 'Tentative')], default='PENDING', max_length=30, verbose_name='RSVP Response Status')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Responded At')),
                ('invitation_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Cryptographic Invitation Token')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_guests', to='meetings.meeting', verbose_name='Meeting')),
            ],
            options={
                'verbose_name': 'Meeting External Guest',
                'verbose_name_plural': 'Meeting External Guests',
            },
        ),
        migrations.CreateModel(
            name='MeetingNotificationOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Recipient Email')),
                ('recipient_type', models.CharField(choices=[('INTERNAL_EMPLOYEE', 'Internal Employee'), ('EXTERNAL_GUEST', 'External Guest')], max_length=30, verbose_name='Recipient Type')),
                ('event_type', models.CharField(max_length=50, verbose_name='Event Type')),
                ('status', models.CharField(default='PENDING_FUTURE_DISPATCH', max_length=30, verbose_name='Dispatch Status')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Email Payload')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_outboxes', to='meetings.meeting', verbose_name='Meeting')),
            ],
            options={
                'verbose_name': 'Meeting Notification Outbox',
                'verbose_name_plural': 'Meeting Notification Outboxes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('response_status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('TENTATIVE', 'Tentative')], db_index=True, default='PENDING', max_length=30, verbose_name='RSVP Response Status')),
                ('response_note', models.CharField(blank=True, max_length=255, verbose_name='Response Note')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Responded At')),
                ('is_organizer', models.BooleanField(default=False, verbose_name='Is Organizer')),
                ('is_optional', models.BooleanField(default=False, verbose_name='Is Optional Invitee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_participations', to='organization.employee', verbose_name='Internal Employee')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='meetings.meeting', verbose_name='Meeting')),
            ],
            options={
                'verbose_name': 'Meeting Participant',
                'verbose_name_plural': 'Meeting Participants',
            },
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['business', 'meeting_date', 'status'], name='idx_meet_biz_date_status'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['business', 'organizer', 'meeting_date'], name='idx_meet_biz_org_date'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['business', 'branch', 'meeting_date'], name='idx_meet_biz_branch_date'),
        ),
        migrations.AddIndex(
            model_name='meetingauditevent',
            index=models.Index(fields=['meeting', '-created_at'], name='idx_meet_audit_created'),
        ),
        migrations.AddConstraint(
            model_name='meetingexternalguest',
            constraint=models.UniqueConstraint(fields=('meeting', 'email'), name='unique_meeting_external_guest'),
        ),
        migrations.AddIndex(
            model_name='meetingparticipant',
            index=models.Index(fields=['meeting', 'response_status'], name='idx_part_meet_status'),
        ),
        migrations.AddIndex(
            model_name='meetingparticipant',
            index=models.Index(fields=['employee', 'response_status'], name='idx_part_emp_status'),
        ),
        migrations.AddConstraint(
            model_name='meetingparticipant',
            constraint=models.UniqueConstraint(fields=('meeting', 'employee'), name='unique_meeting_participant'),
        ),
    ]
